### ISSUE TITLE
links in API are hardcoded to http, causes CORS issues

### ISSUE THREAD

**Issue by moredip** [jhedev/todobackend-haskell#9]
For reasons I don't totally understand it seems that non-https urls don't play nicely with CORS. Unfortunately even if I access the API via https the links generated in the API responses appear to be hardcoded to `http://`. This is causing tests to fail (at least in Chrome): http://preview.todobackend.com/specs/index.html?https://todobackend-scotty.sloppy.zone/todos

**Comment by jhedev** [comment]
Unfortunately I am not able to reproduce this, neither in Chrome nor in Firefox or Safari. 

Each implementation reads the app root via an env variable. This is where the `http://` is hardcoded. As a workaround I could simply change this variable to use `https://` and restart the app.

I'm currently not sure how to solve this at all...

**Comment by jhedev** [comment]
I had a look at other implementations and it looks like most (all) implementations somehow hard code links to http or at least return http links even if the API is accessed via https.

@moredip did you see this issues with other implementations, e.g. python/{django,flask,web.py}?

**Comment by moredip** [comment]
Yes, I'm seeing it with e.g. the python implementations, and not seeing it with implementations that take scheme into account. For example 

http://todobackend.com/specs/index.html?https://todo-backend-webpy.herokuapp.com fails but
http://todobackend.com/specs/index.html?https://todo-backend-webpy.herokuapp.com passes

Still trying to understand what exactly is going on with this - these were passing in the past, so I have to believe that either Chrome changed something around cross-domain policy or Heroku changed something in its routing to try to prevent cross-origin requests. That's the only two feasible explanations I can think of.

**Comment by moredip** [comment]
Digging into this more it looks like at least partially a Heroku issue. I dropped down to using `curl` directly and saw the following:

```
⋙ curl -vv https://todo-backend-sinatra.herokuapp.com/todos/ab39e717-6f63-4f02-bca8-cc25bec31bbf -X OPTIONS
*   Trying 174.129.214.243...
* Connected to todo-backend-sinatra.herokuapp.com (174.129.214.243) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: *.herokuapp.com
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> OPTIONS /todos/ab39e717-6f63-4f02-bca8-cc25bec31bbf HTTP/1.1
> Host: todo-backend-sinatra.herokuapp.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 11 Oct 2015 16:05:15 GMT
< Connection: close
< Content-Type: text/html;charset=utf-8
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,PATCH,HEAD,DELETE,OPTIONS
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Server: thin 1.6.2 codename Doc Brown
< Via: 1.1 vegur
<
* Closing connection 0
Content-Typeaccess-control-allow-originaccess-control-allow-methodsX-XSS-ProtectionX-Content-Type-OptionsX-Frame-Options
```

```
⋙ curl -vv http://todo-backend-sinatra.herokuapp.com/todos/ab39e717-6f63-4f02-bca8-cc25bec31bbf -X OPTIONS
*   Trying 54.197.245.182...
* Connected to todo-backend-sinatra.herokuapp.com (127.0.0.1) port 80 (#0)
> OPTIONS /todos/ab39e717-6f63-4f02-bca8-cc25bec31bbf HTTP/1.1
> Host: todo-backend-sinatra.herokuapp.com
> User-Agent: curl/7.43.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host todo-backend-sinatra.herokuapp.com left intact
curl: (52) Empty reply from server
```

and when I tail logs in Heroku I don't see _any_ traffic coming in for the http request, only the https request. That leads me to believe that Heroku is filtering out OPTIONS requests over http in their routing layer. Which is surprising...

**Comment by jhedev** [comment]
Did you notice that the second command tries to connect to `127.0.0.1`?  Or am I reading this wrong?

**Comment by moredip** [comment]
Woah, weird. I don't understand that at all.

**Comment by moredip** [comment]
Seems like that thing about connecting to `127.0.0.1` is a red herring:

```
⋙ curl -vv http://todo-backend-sinatra.herokuapp.com/todos/ab39e717-6f63-4f02-bca8-cc25bec31bbf -X GET
*   Trying 54.243.98.31...
* Connected to todo-backend-sinatra.herokuapp.com (127.0.0.1) port 80 (#0)
> GET /todos/ab39e717-6f63-4f02-bca8-cc25bec31bbf HTTP/1.1
> Host: todo-backend-sinatra.herokuapp.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 11 Oct 2015 16:33:18 GMT
< Connection: keep-alive
< Content-Type: text/html;charset=utf-8
< Access-Control-Allow-Origin: *
< Content-Length: 278
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< Server: thin 1.6.2 codename Doc Brown
< Via: 1.1 vegur
<
* Connection #0 to host todo-backend-sinatra.herokuapp.com left intact
{"uid":"ab39e717-6f63-4f02-bca8-cc25bec31bbf","title":"blah","order":523,"completed":false,"href":"http://todo-backend-sinatra.herokuapp.com/todos/ab39e717-6f63-4f02-bca8-cc25bec31bbf","url":"http://todo-backend-sinatra.herokuapp.com/todos/ab39e717-6f63-4f02-bca8-cc25bec31bbf"}
```

Still very very odd though.

**Comment by jhedev** [comment]
Hmmm... I ran the commands from above on three different machines now, but I can't reproduce the "`Empty reply from server`" issue. I have no idea why this is failing for you...

**Comment by moredip** [comment]
Finally got to the bottom of this. Turns out that the Cisco VPN client I have installed on my laptop was silently blocking OPTIONS requests over http. :scream: 

@jhedev, thanks so much for your perseverance and patience as I worked through this :)

More info here: http://www.bennadel.com/blog/2559-cisco-anyconnect-vpn-client-may-block-cors-ajax-options-requests.htm#comments_44093

**Comment by jhedev** [comment]
Glad you solved it :)
